### ISSUE TITLE
data collection

### ISSUE THREAD

**Issue by katevcoulter** [MIDS-at-Duke/unifying-data-science-final-project-primaries#12]

**Comment by shttksm** [comment]
For county-level analysis, I found county-level demographic and turnout data from 2008 to 2016 in Colorado.

* Turnout data: https://data.colorado.gov/Elections/2008-Primary-Election-Turnout-Percentage-By-County/96q6-3xgq
* Demographics: https://data.census.gov/cedsci/table?q=Colorado%20county&g=0500000US48089,08071,08081,08107,08057,08069,08123,08075,08103,08045,08077,08029,08085,08113,08033,08083,08067,08007,08101,08109,08051,08097,08037,08049,08125,08121,08087,08013,08059,08031,08001,08117,08065,08093,08015,08023,08021,08009,08063,08115,08095,08017,08061,08011,08099,08089,08025,08073,08039,08005,08019,08047,08035,08041,08119,08043,08027,08055,08003,08105,08079,08053,08111,08091,08014&tid=ACSDP5Y2010.DP05&vintage=2018&layer=VT_2018_050_00_PY_D1

I think I can use demographics in 2018 instead of one in 2020 for analysis if the demographic composition might not change drastically. But, I could not find county-level turnout data in Colorado (it probably will be available later in the website above...)

**Comment by aberman6** [comment]
Hi Shota. I thought on our call we had talked about collecting data for Maine. Were you able to have any more luck there?

**Comment by aberman6** [comment]
We weren't able to collect data for Maine so we pivoted to Colorado 

Colorado turnout data : https://www.sos.state.co.us/pubs/elections/Results/Archives.html
Colorado demo data : https://demography.dola.colorado.gov/population/data/race-estimate/
